default: &default
  adapter: postgresql
  encoding: unicode
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  errors:
    <<: *default
    database: number_gaps_development_errors
    migrations_paths: db/errors_migrate

production:
  errors:
    <<: *default
    database: number_gaps_production_errors
    migrations_paths: db/errors_migrate
  # cache:
  #   <<: *primary_production
  #   database: number_gaps_production_cache
  #   migrations_paths: db/cache_migrate
  # queue:
  #   <<: *primary_production
  #   database: number_gaps_production_queue
  #   migrations_paths: db/queue_migrate
  # cable:
  #   <<: *primary_production
  #   database: number_gaps_production_cable
  #   migrations_paths: db/cable_migrate
